name: ip4cf

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 playwright

    - name: Install Playwright browsers
      run: |
        playwright install

    - name: Run Python script
      run: |
        python ip4.py  # 确保这是脚本文件名

    - name: Configure Git
      run: |
        git config --global user.name "weizhe940605"
        git config --global user.email "weizhe978@gmail.com"

    - name: Pull latest changes
      run: |
        git stash
        git pull --rebase origin main || echo "No remote changes to pull"
        git stash pop || echo "No local changes to reapply"

    - name: Commit and push generated files
      run: |
        # 强制添加修改的文件
        git add -A
        git commit -m "Auto-update CSV and TXT files" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
